module.exports = [
    "Viet Nam",
    "China",
    "Italy",
    "Spain",
    "USA",
    "Germany",
    "Iran",
    "France",
    "S. Korea",
    "Switzerland",
    "UK",
    "Netherlands",
    "Belgium",
    "Austria",
    "Norway",
    "Sweden",
    "Portugal",
    "Canada",
    "Denmark",
    "Australia",
    "Brazil",
    "Malaysia",
    "Japan",
    "Czechia",
    "Turkey",
    "Israel",
    "Luxembourg",
    "Ireland",
    "Pakistan",
    "Diamond Princess",
    "Finland",
    "Thailand",
    "Iceland",
    "Poland",
    "Chile",
    "Ecuador",
    "Greece",
    "Indonesia",
    "Qatar",
    "Romania",
    "Singapore",
    "Saudi Arabia",
    "Slovenia",
    "Philippines",
    "India",
    "Bahrain",
    "Estonia",
    "Peru",
    "Russia",
    "Egypt",
    "Hong Kong",
    "Mexico",
    "Lebanon",
    "Panama",
    "South Africa",
    "Croatia",
    "Iraq",
    "Argentina",
    "Colombia",
    "Armenia",
    "Serbia",
    "Kuwait",
    "Slovakia",
    "Bulgaria",
    "Taiwan",
    "San Marino",
    "UAE",
    "Algeria",
    "Latvia",
    "Uruguay",
    "Hungary",
    "Costa Rica",
    "North Macedonia",
    "Dominican Republic",
    "Morocco",
    "Lithuania",
    "Jordan",
    "Bosnia and Herzegovina",
    "Faeroe Islands",
    "Albania",
    "Andorra",
    "Cyprus",
    "Brunei",
    "Moldova",
    "Sri Lanka",
    "Belarus",
    "Tunisia",
    "Malta",
    "Venezuela",
    "New Zealand",
    "Burkina Faso",
    "Palestine",
    "Guadeloupe",
    "Senegal",
    "Georgia",
    "Kazakhstan",
    "Azerbaijan",
    "Cambodia",
    "Oman",
    "Trinidad and Tobago",
    "Ukraine",
    "Réunion",
    "Uzbekistan",
    "Cameroon",
    "Martinique",
    "Liechtenstein",
    "Channel Islands",
    "Bangladesh",
    "Guam",
    "Honduras",
    "Afghanistan",
    "DRC",
    "Puerto Rico",
    "Paraguay",
    "Nigeria",
    "Cuba",
    "Ghana",
    "Macao",
    "Jamaica",
    "Bolivia",
    "Guyana",
    "Mauritius",
    "Monaco",
    "French Guiana",
    "Guatemala",
    "Rwanda",
    "Montenegro",
    "Togo",
    "French Polynesia",
    "Barbados",
    "Ivory Coast",
    "Kyrgyzstan",
    "Maldives",
    "Tanzania",
    "Mayotte",
    "Gibraltar",
    "Mongolia",
    "Ethiopia",
    "Aruba",
    "Kenya",
    "Seychelles",
    "Equatorial Guinea",
    "U.S. Virgin Islands",
    "Gabon",
    "Isle of Man",
    "Saint Martin",
    "Suriname",
    "Bahamas",
    "New Caledonia",
    "Eswatini",
    "Cayman Islands",
    "Curaçao",
    "Cabo Verde",
    "CAR",
    "Congo",
    "El Salvador",
    "Liberia",
    "Madagascar",
    "Namibia",
    "St. Barth",
    "Zimbabwe",
    "Sudan",
    "Angola",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Fiji",
    "Greenland",
    "Guinea",
    "Haiti",
    "Mauritania",
    "Nicaragua",
    "Saint Lucia",
    "Zambia",
    "Nepal",
    "Antigua and Barbuda",
    "Chad",
    "Djibouti",
    "Eritrea",
    "Gambia",
    "Vatican City",
    "Montserrat",
    "Niger",
    "Papua New Guinea",
    "St. Vincent Grenadines",
    "Sint Maarten",
    "Somalia",
    "Timor-Leste",
    "Uganda",
]